sudo: required
services:
  - xvfb
  - postgresql
addons:
    chrome: stable
    postgresql: "10"
language: php
dist: bionic
node_js:
 - "10"

php:
  - 7.2
#  - 7.3

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - yarn install --no-progress

before_script:
  - export DISPLAY=:99.0
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - sudo -iu postgres sh -c "createuser test_ln; createdb test_ln --owner=test_ln; psql -c \"alter user test_ln with encrypted password 'test_ln';\""
  - cp .env.testing.travis .env
  - php artisan migrate:fresh --seed
  - NUXT_PORT=4000 yarn run dev &
  - php artisan serve --port=3000 &

script:
  - yarn run lint
  - find ./{app,bootstrap,database,config,resources/views,routes,tests}/ -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected")
  - yarn run generate
  - vendor/bin/phpunit tests/Unit
  - vendor/bin/phpunit tests/Feature
  - php artisan dusk

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache/files
