sudo: required
services:
  - xvfb
addons:
    chrome: stable
language: php
dist: bionic
node_js:
 - "10"

php:
  - 7.2
#  - 7.3

install:
  - node -v
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - yarn install --no-progress

before_script:
  - export DISPLAY=:99.0
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.testing .env
  - yarn run lint
  - yarn run generate

script:
  - vendor/bin/phpunit tests/Unit
  - vendor/bin/phpunit tests/Feature
  - php artisan dusk

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache/files
