# @link https://www.netlify.com/docs/netlify-toml-reference/
# @todo test and verify this

# handle SPA (required because netlify does not support SSR)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# handle /api (send /api calls to your real backend)
[[redirects]]
  from = "/api/*"
  to = "https://api.ln.d/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
#    X-Api-Key = "some-api-key-string"
